from snakemake.utils import min_version


##### set minimum snakemake version #####
min_version("8.4.1")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/locus_breaker.smk"
include: "rules/mr_instruments.smk"
include: "rules/backward_literature.smk"


rule all:
    input:
        get_final_output(),
