executor: slurm
jobs: 300
software-deployment-method:
   - conda
   - apptainer
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 8
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq
    # slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5
set-resources:
    break_locus:
        mem_mb: 4096 + attempt * 2048
        threads: 1
    rename_LB:
        mem_mb: 2048  + attempt * 2048
        threads: 1
    collect_loci:
        mem_mb: 8192 + attempt * 2048
        threads: 1
    select_best_SNP_from_LocusBreaker:
        mem_mb: 2048 + attempt * 2048
        threads: 1
    backward_literature_LB:
        mem_mb: 2048 + attempt * 2048
        threads: 1
    heterogenous_filter:
        mem_mb: 2048 + attempt * 2048
        threads: 1
