input: "LB" # This flag can be LB or conditional

run:
  delivery: False

# paths
workspace_path: 'results'
destination_path: 'destination'
sumstats_path: 'config/local.txt'

# LB
path_code: "workflow/scripts/"
labels:
  chr_label: "'#CHR'"
  pos_label: "POS"
  snpid_label: "SNPID"
#  key_label: "PREVIOUS_ID"
#  ea_label: "EA"
#  oa_label: "NEA"
#  eaf_label: "EAF"
#  beta_label: "BETA"
#  se_label: "SE"
#  p_label: "MLOG10P"
#  n_label: "N"
thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
#  p3: 1.256913021618904e-11
#  p4: 1e-06
#  maf: 1e-04
#  ppp: 0.99
  hole: 250000

# MR
mapping_filepath: 'data/MR/mapped_gene_file_GRCh37_21052025.txt'
array_list_path: "data/MR/"
params:
  nef: 3978
