input: "LB" # This flag can be LB or conditional or run_LB
#LB_file: "data/collected_loci_excluding_mhc.csv"
LB_file: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/16-Dec-24_collected_loci_excluding_mhc.csv"

run:
  delivery: FALSE

# paths
workspace_path: 'results_test'
destination_path: 'dest'


# LB
sumstats_list: 'config/qced_filtered_meta_path.txt'
labels:
  chr_label: "'##CHR'"
  pos_label: "POS"
#  snpid_label: "SNPID"
#  key_label: "PREVIOUS_ID"
#  ea_label: "EA"
#  oa_label: "NEA"
#  eaf_label: "EAF"
#  beta_label: "BETA"
#  se_label: "SE"
  p_label: "MLOG10P"
#  n_label: "N"
thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
#  p3: 1.256913021618904e-11
#  p4: 1e-06
#  maf: 1e-04
#  ppp: 0.99
  hole: 3000000
loci_selection:
  NLP12: 0
  MHC: 0
  build: 37


# MR
#sumstats_path: '/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped/output'
mapping_filepath: '/exchange/healthds/pQTL/Reference_datasets_for_QC_proteomics/Cis_trans_mapping/somascan_tss_ncbi_grch37_ensembl_version_20241216.txt'
array_list_path: "data"
gtf_file: '/exchange/healthds/public_data/reference_genomes/GRCh37/GCF_000001405.25_GRCh37.p13_genomic.gtf'
params:
  nef: 3978
  Isquare: 90

# Backward literature
BL_config_file: 'config/config_backward_literature.json'

# Single studies to be concatenated
single_studies:
  - CHRIS
  - INTERVAL

# hotspot_finder
hotspot_finder:
  hotspot_window_size: 5000000
  chr_col: "chr"
  start_col: "start"
  end_col: "end"
  hotspot_threshold: 50
  lonespot_window_size: 10000000
  lonespot_threshold: 1
