name: r_MR
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies: #R>=4.3
  - r-base=4.3.3
  - r-optparse=1.7.4
  - r-tidyverse=2.0.0
  - r-dplyr=1.1.4
  - r-data.table=1.15.4
  - r-R.utils=2.12.3
  - bioconductor-iranges=2.36.0
  - bioconductor-genomicranges=1.54.1
  - bioconductor-rtracklayer=1.62.0
  -
